[project]
name = "palinis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.29.0",
    "email-validator>=2.2.0",
    "pydantic>=2.10.0",
    "python-dotenv>=1.2.0",
    "python-fasthtml>=0.12.47",
]
